server:
  port: 8089

  spring:
    application:
      name: JobSearch

      spring:
        url=jdbc:h2:./db/test;AUTO_SERVER=TRUE
      password: qwerty
    driver-class-name=org:
      h2:
        Driver:
